# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        visites:
            uri_prefix: /images/visites
            upload_destination: '%kernel.project_dir%/public/images/visites'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer